### ISSUE TITLE
Image collection for MOD13Q1

### ISSUE THREAD

**Issue by gilbertocamara** [appelmar/gdalcubes#23]
Hi, Marius and Edzer,
Congratulation for the gdalcubes package!! Great work!! I am starting to work on integrating "gdalcubes" with the SITS (Satellite Image Time Series) package, available on https://github.com/e-sensing/sits. One of the data sets we use a lot is MOD13Q1, which provides 250 m resolution imagery (see for example, https://doi.org/10.1016/j.isprsjprs.2018.08.007). Would it be asking too much from you to include the MOD13Q1 format in your image collection format?

**Comment by appelmar** [comment]
Great, let me know if I can help you with the integration. I've added a collection format for MOD13Q1 to the package (see https://github.com/appelmar/gdalcubes_R/blob/cran-v0.2.0/inst/formats/MxD13Q1.json). The format includes NDVI, EVI, red, MIR, NIR, blue, VI quality, and pixel reliability bands but so far ignores view zenith angle, sun zenith angle, relative azimuth angle, and composite day of the year. Does this work for you?

I am planning a CRAN submission of the package these days, so the format should be available also in the next version on CRAN.

**Comment by gilbertocamara** [comment]
Hi Marius

Great!! Thanks for the quick response. As soon as I have something, I will contact you.

Best
Gilberto

**Comment by appelmar** [comment]
Looking forward to it, I'll close this issue for now.
